### ISSUE TITLE
[Bug] Type error in NgDocComponentContent

### ISSUE THREAD

**Issue by semicolin** [skoropadas/ng-doc#41]
### Is this a regression?

Yes

### Description

After upgrading from 15.10.5 to 15.11.1, I see the following error

### Please provide the exception or error you saw

```true
Error: node_modules/@ng-doc/ui-kit/types/content.d.ts:8:5 - error TS2416: Property 'createInjector' in type 'NgDocComponentContent<T, C>' is not assignable to the same property in base type 'PolymorpheusComponent<T, C>'.
  Type '(injector: Injector, context: C, providers?: StaticProvider[] | undefined) => Injector' is not assignable to type '<C>(injector: Injector, useValue?: C | undefined) => Injector'.
    Types of parameters 'context' and 'useValue' are incompatible.
      Type 'C | undefined' is not assignable to type 'C'.
        'C' could be instantiated with an arbitrary type which could be unrelated to 'C | undefined'.

8     createInjector(injector: Injector, context: C, providers?: StaticProvider[]): Injector;
      ~~~~~~~~~~~~~~
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.15.0

**Comment by skoropadas** [comment]
Thank you for the bug report! It was my mistake, I didn't lock the versions of the dependencies, and apparently they released a new minor version of `@tinkoff/ng-polymorpheus` breaking backward compatibility of types. I didn't notice this because I had an old `package-lock.json`, but after deleting it and installing the dependencies from scratch, I get the same error.

In any case, I will fix this as soon as possible and lock all dependencies to avoid similar bugs in the future.
